mappings:
  ItemPercentDiscount: SilverShop\Discounts\Actions\ItemPercentDiscount
  ItemDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\ItemDiscountConstraint
  DiscountReport: SilverShop\Discounts\Admin\DiscountReport
  DiscountModelAdmin: SilverShop\Discounts\Admin\DiscountModelAdmin
  CheckoutStepDiscount: SilverShop\Discounts\Checkout\Step\CheckoutStepDiscount
  CouponForm: SilverShop\Discounts\Form\CouponForm
  GridField_LinkComponent: SilverShop\Discounts\Form\GridField_LinkComponent
  DiscountedOrderExtension: SilverShop\Discounts\Extensions\DiscountedOrderExtension
  ProductVariationDiscountExtension: SilverShop\Discounts\Extensions\ProductVariationDiscountExtension
  ProductDiscountExtension: SilverShop\Discounts\Extensions\ProductDiscountExtension
  SpecificPricingExtension: SilverShop\Discounts\Extensions\SpecificPricingExtension
  DiscountedOrderItem: SilverShop\Discounts\Extensions\DiscountedOrderItem
  CouponFormCheckoutDecorator: SilverShop\Discounts\Extensions\CouponFormCheckoutDecorator
  OrderDiscount: SilverShop\Discounts\Model\OrderDiscount
  OrderCoupon: SilverShop\Discounts\Model\OrderCoupon
  GiftVoucherProduct: SilverShop\Discounts\Model\GiftVoucherProduct
  GiftVoucherProduct_Controller: SilverShop\Discounts\Model\GiftVoucherProduct_Controller
  GiftVoucherFormValidator: SilverShop\Discounts\Model\GiftVoucherFormValidator
  GiftVoucher_OrderItem: SilverShop\Discounts\Model\GiftVoucherOrderItem
  Discount: SilverShop\Discounts\Model\Discount
  PartialUseDiscount: SilverShop\Discounts\Model\PartialUseDiscount
  OrderDiscountModifier: SilverShop\Discounts\Model\Modifiers\OrderDiscountModifier
  OrderCouponTest: SilverShop\Discounts\Tests\OrderCouponTest
  PartialUseDiscountTest: SilverShop\Discounts\Tests\PartialUseDiscountTest
  DiscountReportTest: SilverShop\Discounts\Tests\DiscountReportTest
  CouponFormTest: SilverShop\Discounts\Tests\CouponFormTest
  OrderDiscountTest: SilverShop\Discounts\Tests\OrderDiscountTest
  SpecificPriceTest: SilverShop\Discounts\Tests\SpecificPriceTest
  GiftVoucherTest: SilverShop\Discounts\Tests\GiftVoucherTest
  CalculatorTest: SilverShop\Discounts\Tests\CalculatorTest
  DatetimeDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\DatetimeDiscountConstraintTest
  CategoriesDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\CategoriesDiscountConstraintTest
  ProductsDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\ProductsDiscountConstraintTest
  ProductTypeDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\ProductTypeDiscountConstraintTest
  UseLimitDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\UseLimitDiscountConstraintTest
  MembershipDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\MembershipDiscountConstraintTest
  ValueDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\ValueDiscountConstraintTest
  GroupDiscountConstraintTest: SilverShop\Discounts\Tests\Constraints\GroupDiscountConstraintTest
  CategoriesDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\CategoriesDiscountConstraint
  DiscountConstraint: SilverShop\Discounts\Extensions\Constraints\DiscountConstraint
  UseLimitDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\UseLimitDiscountConstraint
  ValueDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\ValueDiscountConstraint
  GroupDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\GroupDiscountConstraint
  CodeDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\CodeDiscountConstraint
  DatetimeDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\DatetimeDiscountConstraint
  MembershipDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\MembershipDiscountConstraint
  ProductsDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\ProductsDiscountConstraint
  ProductTypeDiscountConstraint: SilverShop\Discounts\Extensions\Constraints\ProductTypeDiscountConstraint
