---
Name: shopdiscount
---
LeftAndMain:
  extra_requirements_css:
    - shop_discount/css/OrderCouponAdmin.css
Product:
  extensions:
    - ProductDiscountExtension
ProductVariation:
  extensions:
    - ProductVariationDiscountExtension
Order:
  extensions:
    - DiscountedOrderExtension
Product_OrderItem:
  extensions:
    - DiscountedOrderItem
Discount:
  constraints:
    - ZonesDiscountConstraint
    - CategoriesDiscountConstraint
    - ProductsDiscountConstraint
    - GroupDiscountConstraint
    - MembershipDiscountConstraint
    - DatetimeDiscountConstraint
    - ValueDiscountConstraint
    - UseLimitDiscountConstraint
    - CodeDiscountConstraint
