---
Name: shopdiscount
---
LeftAndMain:
  extra_requirements_css:
    - shop_discount/css/OrderCouponAdmin.css
Discount:
  constraints:
    - DatetimeDiscountConstraint
    - ValueDiscountConstraint
    - GroupDiscountConstraint
    - ZonesDiscountConstraint
    - ProductsDiscountConstraint
    - CategoriesDiscountConstraint
