---
Name: shopdiscount
---
LeftAndMain:
  extra_requirements_css:
    - shop_discount/css/OrderCouponAdmin.css
Product_OrderItem:
  extensions:
    - DiscountedOrderItem
CheckoutPage_Controller:
  extensions:
    - CouponFormCheckoutDecorator
Discount:
  constraints:
    - DatetimeDiscountConstraint
    - UseLimitDiscountConstraint
    - ValueDiscountConstraint
    - GroupDiscountConstraint
    - ZonesDiscountConstraint
    - ProductsDiscountConstraint
    - CategoriesDiscountConstraint
