---
Name: silvershop-discounts
---
SilverShop\Page\Product:
  extensions:
    - SilverShop\Discounts\Extensions\ProductDiscountExtension
SilverShop\Model\Variation\Variation:
  extensions:
    - SilverShop\Discounts\Extensions\ProductVariationDiscountExtension
SilverShop\Model\Order:
  extensions:
    - SilverShop\Discounts\Extensions\DiscountedOrderExtension
SilverShop\Model\OrderItem:
  extensions:
    - SilverShop\Discounts\Extensions\DiscountedOrderItem
SilverShop\Discounts\Model\Discount:
  constraints:
    - SilverShop\Discounts\Extensions\Constraints\CategoriesDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\ProductsDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\GroupDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\MembershipDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\DatetimeDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\ValueDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\UseLimitDiscountConstraint
    - SilverShop\Discounts\Extensions\Constraints\CodeDiscountConstraint
