---
Name: shopdiscount
---
LeftAndMain:
  extra_requirements_css:
    - shop_discount/css/OrderCouponAdmin.css
Product_OrderItem:
  extensions:
    - DiscountedOrderItem
Discount:
  constraints:
    - DatetimeDiscountConstraint
    - UseLimitDiscountConstraint
    - ValueDiscountConstraint
    - GroupDiscountConstraint
    - ZonesDiscountConstraint
    - ProductsDiscountConstraint
    - CategoriesDiscountConstraint
    - CodeDiscountConstraint
